[font]
size = 22.0

[font.normal]
family = "Mononoki Nerd Font Mono"
style = "Regular"

[window]
opacity = 0.7

[window.padding]
x = 15
y = 15

[window.dimensions]
columns=146
lines=42

[colors.primary]
foreground = '#D8DEE9'
background = '#111111'
